echo "CERTOS"
cat ex/certo01.txt | ./build/main
cat ex/certo02.txt | ./build/main
cat ex/certo03.txt | ./build/main
cat ex/certo04.txt | ./build/main
cat ex/certo05.txt | ./build/main
cat ex/certo06.txt | ./build/main
cat ex/certo07.txt | ./build/main
cat ex/certo08.txt | ./build/main
cat ex/certo09.txt | ./build/main
cat ex/certo10.txt | ./build/main
cat ex/certo11.txt | ./build/main
cat ex/certo12.txt | ./build/main
cat ex/certo13.txt | ./build/main
cat ex/certo14.txt | ./build/main
cat ex/certo15.txt | ./build/main
cat ex/certo16.txt | ./build/main
cat ex/certo17.txt | ./build/main
cat ex/certo18.txt | ./build/main
cat ex/certo19.txt | ./build/main
cat ex/certo20.txt | ./build/main
echo "ERRADOS"
cat ex/errado01.txt | ./build/main
cat ex/errado02.txt | ./build/main
cat ex/errado03.txt | ./build/main
cat ex/errado04.txt | ./build/main
cat ex/errado05.txt | ./build/main
cat ex/errado06.txt | ./build/main
cat ex/errado07.txt | ./build/main
cat ex/errado08.txt | ./build/main
cat ex/errado09.txt | ./build/main
cat ex/errado10.txt | ./build/main
cat ex/errado11.txt | ./build/main
cat ex/errado12.txt | ./build/main
cat ex/errado13.txt | ./build/main
cat ex/errado14.txt | ./build/main
cat ex/errado15.txt | ./build/main
cat ex/errado16.txt | ./build/main
cat ex/errado17.txt | ./build/main
cat ex/errado18.txt | ./build/main
cat ex/errado19.txt | ./build/main
cat ex/errado20.txt | ./build/main
