./build/main ex/certo01.txt ex/saida01.txt
./build/main ex/certo02.txt ex/saida02.txt
./build/main ex/certo03.txt ex/saida03.txt
./build/main ex/certo04.txt ex/saida04.txt
./build/main ex/certo05.txt ex/saida05.txt
./build/main ex/certo06.txt ex/saida06.txt
./build/main ex/certo07.txt ex/saida07.txt
./build/main ex/certo08.txt ex/saida08.txt
./build/main ex/certo09.txt ex/saida09.txt
./build/main ex/certo10.txt ex/saida10.txt
./build/main ex/certo11.txt ex/saida11.txt
./build/main ex/certo12.txt ex/saida12.txt
./build/main ex/certo13.txt ex/saida13.txt
./build/main ex/certo14.txt ex/saida14.txt
./build/main ex/certo15.txt ex/saida15.txt
./build/main ex/certo16.txt ex/saida16.txt
./build/main ex/certo17.txt ex/saida17.txt
./build/main ex/certo18.txt ex/saida18.txt
./build/main ex/certo19.txt ex/saida19.txt
./build/main ex/certo20.txt ex/saida20.txt
